db_uri: "postgresql://user:pwd@ip:5432/mydb"
log_file: "./cleaner.log"
dry_run: false
auto_discover_related: true

skip_tables: ["tenant"]
skip_columns: []

tables:
  - name: "tableA"
    key_columns: ["id"]            
    date_column: "timestamp"        
    expire_days: 70
    batch_size: 1000
    archive: true
    time_out: 0 # 0 means not set timeout
    archive_path: "./archive"
    related:
      - name: "tableA1"
        parent_table: "tableA" 
        mapping:
          parent_columns: ["id"]
          child_columns: ["A1_id"]
      - name: "TableA11"
        parent_table: "tableA1"
        mapping:
          parent_columns: ["A1_inc"]
          child_columns: ["TableA11_inc"]       
      # - name: "xxx"
        # Optionalï¼šextra filters
        # conditions:
        #   - column: "tenant_id"
        #     op: "="
        #     value: "acme"
